// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "Never accepts user input", Scope = "member", Target = "~M:GrouperLib.Database.DocumentDb.GetDocumentEntries(System.String,System.Collections.Generic.IDictionary{System.String,System.Object})~System.Threading.Tasks.Task{System.Collections.Generic.IList{GrouperLib.Database.GrouperDocumentEntry}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Pending>", Scope = "member", Target = "~M:GrouperLib.Database.DocumentDb.ExecuteStoredProcedureAsync(System.String,System.Collections.Generic.IDictionary{System.String,System.Object})~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Pending>", Scope = "member", Target = "~M:GrouperLib.Database.LogDb.InternalGetEventLogItemsAsync(System.String,System.Collections.Generic.IDictionary{System.String,System.Object})~System.Threading.Tasks.Task{System.Collections.Generic.IList{GrouperLib.Logging.EventLogItem}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Pending>", Scope = "member", Target = "~M:GrouperLib.Database.LogDb.InternalGetOperationalLogItemsAsync(System.String,System.Collections.Generic.IDictionary{System.String,System.Object})~System.Threading.Tasks.Task{System.Collections.Generic.IList{GrouperLib.Logging.OperationalLogItem}}")]
