//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrouperLib.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrouperLib.Language.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to validate document contents.
        /// </summary>
        public static string DefaultValidationError {
            get {
                return ResourceManager.GetString("DefaultValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change ratio is below limit. No changes are made to the group members.
        /// </summary>
        public static string ErrorBelowChangeLimit {
            get {
                return ResourceManager.GetString("ErrorBelowChangeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON document does not represent a valid Grouper document.
        /// </summary>
        public static string ErrorGrouperDocumentNotValid {
            get {
                return ResourceManager.GetString("ErrorGrouperDocumentNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured.
        /// </summary>
        public static string GenericErrorMessage {
            get {
                return ResourceManager.GetString("GenericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to deserialize JSON to intermediate Grouper document. Check if JSON represents a Grouper document.
        /// </summary>
        public static string ValidationCouldNotDeserializeJson {
            get {
                return ResourceManager.GetString("ValidationCouldNotDeserializeJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document ID is missing or not a valid GUID (ID: {0}).
        /// </summary>
        public static string ValidationErrorDocumentIdNotValid {
            get {
                return ResourceManager.GetString("ValidationErrorDocumentIdNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The same member object can only appear once for each group (Member source: {0}, Member action: {1}, Member count: {2}).
        /// </summary>
        public static string ValidationErrorDuplicateMemberObject {
            get {
                return ResourceManager.GetString("ValidationErrorDuplicateMemberObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The same rule name and value cannot appear more than once (Rule name: {0}, Rule value: {1}).
        /// </summary>
        public static string ValidationErrorDuplicateRule {
            get {
                return ResourceManager.GetString("ValidationErrorDuplicateRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule name can only appear once for every rulse set (Rule name: {0}).
        /// </summary>
        public static string ValidationErrorDuplicateRuleName {
            get {
                return ResourceManager.GetString("ValidationErrorDuplicateRuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group ID is missing or not a valid GUID (ID: {0}).
        /// </summary>
        public static string ValidationErrorGroupIdNotValid {
            get {
                return ResourceManager.GetString("ValidationErrorGroupIdNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name is missing or empty.
        /// </summary>
        public static string ValidationErrorGroupNameIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ValidationErrorGroupNameIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing interval hint must be greater or equal to zero.
        /// </summary>
        public static string ValidationErrorIllegalInterval {
            get {
                return ResourceManager.GetString("ValidationErrorIllegalInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid combination of group store and member source (Group store: {0}, Member source: {1}).
        /// </summary>
        public static string ValidationErrorInvalidCombinationOfGroupStoreAndMemberSource {
            get {
                return ResourceManager.GetString("ValidationErrorInvalidCombinationOfGroupStoreAndMemberSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This combination of rules is not valid for selected member source (Member source: {0}).
        /// </summary>
        public static string ValidationErrorInvalidCombinationOfRules {
            get {
                return ResourceManager.GetString("ValidationErrorInvalidCombinationOfRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group store is missing or invalid (Group store: {0}).
        /// </summary>
        public static string ValidationErrorInvalidGroupStore {
            get {
                return ResourceManager.GetString("ValidationErrorInvalidGroupStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member action is missing or invalid. Valid actions are &quot;Include&quot; or &quot;Exclude&quot; (Member action: {0}).
        /// </summary>
        public static string ValidationErrorInvalidMemberAction {
            get {
                return ResourceManager.GetString("ValidationErrorInvalidMemberAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member source is missing or invalid (Member source: {0}).
        /// </summary>
        public static string ValidationErrorInvalidMemberSource {
            get {
                return ResourceManager.GetString("ValidationErrorInvalidMemberSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner action is missing or invalid. Valid actions are &quot;AddAll&quot;, &quot;KeepExisting&quot; or &quot;MatchSource&quot; (Owner action: {0})&quot;.
        /// </summary>
        public static string ValidationErrorInvalidOwnerAction {
            get {
                return ResourceManager.GetString("ValidationErrorInvalidOwnerAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule name is missing or can not be used in combination with the selected member source (Rule name: {0}, Member source: {1}).
        /// </summary>
        public static string ValidationErrorInvalidRuleName {
            get {
                return ResourceManager.GetString("ValidationErrorInvalidRuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule value is not a valid UserPrincipalName (Rule value: {0}).
        /// </summary>
        public static string ValidationErrorInvalidUpn {
            get {
                return ResourceManager.GetString("ValidationErrorInvalidUpn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rules found for member object.
        /// </summary>
        public static string ValidationErrorMemberObjectHasNoRules {
            get {
                return ResourceManager.GetString("ValidationErrorMemberObjectHasNoRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No member objects found.
        /// </summary>
        public static string ValidationErrorNoMemberObjects {
            get {
                return ResourceManager.GetString("ValidationErrorNoMemberObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule value is invalid (Rule name: {0}, Rule value: {1}).
        /// </summary>
        public static string ValidationErrorRuleValueDoesNotValidate {
            get {
                return ResourceManager.GetString("ValidationErrorRuleValueDoesNotValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule value is missing (Rule: {0}).
        /// </summary>
        public static string ValidationErrorRuleValueIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ValidationErrorRuleValueIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The same group cannot be used both as member source and target group.
        /// </summary>
        public static string ValidationErrorSourceGroupSameAsTarget {
            get {
                return ResourceManager.GetString("ValidationErrorSourceGroupSameAsTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The validator does not recognize the group store {0}.
        /// </summary>
        public static string ValidationErrorStoreNotRecognized {
            get {
                return ResourceManager.GetString("ValidationErrorStoreNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while parsing JSON document on line {0} column {1}. The error message is: {2}.
        /// </summary>
        public static string ValidationJsonParsingError {
            get {
                return ResourceManager.GetString("ValidationJsonParsingError", resourceCulture);
            }
        }
    }
}
